---
-   name:           "etcd :: cluster :: add new node :: script-copy"
    copy:
        src:        bin/etcd-cluster-add-new-node.sh
        dest:       /root/etcd-cluster-add-new-node.sh
        mode:       0755

-   name:           "etcd :: cluster :: add new node :: script-execute"
    command:        /root/etcd-cluster-add-new-node.sh {{ inventory_hostname }} {{ new_node_hostname }} {{ new_node_name_fqdn }} {{ new_node_ip }}
    register:       etcd_cluster_add_new_node_cmd
    changed_when:   "etcd_cluster_add_new_node_cmd.stdout.find('SKIPPING') != 0"
