---



###
### Require confirmation first
###
#
-   include:   request-confirmation.yml



###
### TASKS to execute
###
#
-   name:        "etcd :: cluster :: destroy"
    hosts:       etcd_nodes
    tasks:



        ### Stop daemons and destroy cluster data
        #
        - include:   ./tasks/etcd-daemon-stop.yml
        - include:   ./tasks/etcd-data-destroy.yml
